name: myplatform
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+4
environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  lottie: ^2.3.2
  email_validator: ^2.1.17
  provider: ^6.0.5
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.3
  firebase_messaging: ^14.6.5
  firebase_app_check: ^0.1.5+1
  awesome_dialog: ^3.1.0
  font_awesome_flutter: ^10.4.0
  image_picker: ^1.0.1
  firebase_storage: ^11.2.5
  date_field: ^3.0.5
  csc_picker: ^0.2.7
  phone_number: ^2.0.1
  intl_phone_field: ^3.2.0
  dob_input_field: ^2.0.0
  url_launcher: ^6.1.11
  permission_handler: ^10.4.3
  flutter_local_notifications: ^15.1.0+1
  new_version: ^0.3.1
  wakelock: ^0.6.2
  time_range_picker: ^2.2.0
  flutter_launcher_icons: ^0.13.1
  flutter_signature_pad: ^3.0.1
  flutter_pw_validator: ^1.6.0
  flutter_screenutil: ^5.9.0
  file_picker: ^5.2.10
  open_app_file: ^4.0.2
  ed_screen_recorder: ^0.0.13
  easy_pdf_viewer: ^1.0.7
  flutter_slidable: ^3.0.0
  story: ^1.1.0
dependency_overrides:
  package_info_plus: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - images/